# Generated by Django 4.0.4 on 2022-05-31 14:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockMarket', '0004_portafolio_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessBoard',
        ),
        migrations.RemoveField(
            model_name='portafoliouser',
            name='user',
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, size=None),
        ),
        migrations.DeleteModel(
            name='MyTestModel',
        ),
        migrations.DeleteModel(
            name='PortafolioUser',
        ),
    ]
