# Generated by Django 4.0.4 on 2022-06-03 08:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stockMarket', '0006_stock_remove_portafolio_tags_portafolio_userstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
