# Generated by Django 4.0.4 on 2022-06-04 01:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stockMarket', '0007_portafolio_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='country',
            field=django_countries.fields.CountryField(default='Select Country', max_length=2),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
