# Generated by Django 4.0.4 on 2022-07-06 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockMarket', '0009_remove_portafolio_user_portafolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='user',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
